import './style/variables.css'
import './style/style.css'
import './style/nav.css'
import './style/sideMenu.css'
import './style/header.css'
import './style/projects.css'
import './style/skills.css'
import './style/education.css'
import './style/contacts.css'
import './style/footer.css'

import './style/stackCard.css'

import './style/projectsView.css'
import './style/responsive.css'
